/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajo;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;
import javax.swing.Timer;

public class transferir extends javax.swing.JDialog {

    private int segundos = 0, centecimas_desegundos = 0, variante = 0;
    private Timer tiempo;
    private ActionListener accionnes = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            centecimas_desegundos++;
            if (centecimas_desegundos == 100) {
                segundos++;
                centecimas_desegundos = 0;
            }
            if (segundos == 31) {
                segundos = 0;
            }
            actualizartexto();
        }
    };

    private void actualizartexto() {
        if (segundos == 30) {
            variante = (int) (Math.random() * 1000000);
            codigo.setText("CODIGO DE MOVIENTO BANCARIO: " + variante);
        }
    }

    private int numeroescogido = 0;

    public transferir(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        variante = (int) (Math.random() * 1000000);
        tiempo = new Timer(10,accionnes);
        tiempo.start();
        codigo.setText("CODIGO DE MOVIENTO BANCARIO: " + variante);
        actualizartexto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        texdinero = new javax.swing.JTextField();
        textras = new javax.swing.JTextField();
        texcodigo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        texcvv = new javax.swing.JTextField();
        codigo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jLabel1.setText("CODIGO DE MOVIENTO BANCARIO:");

        jLabel2.setText("NUMERO DE TRANSFERENCIAS BANCARIAS:");

        jLabel3.setText("CANTIDA DE DINERO:");

        textras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textrasActionPerformed(evt);
            }
        });

        texcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texcodigoActionPerformed(evt);
            }
        });

        jButton1.setText("INGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("CVV");

        codigo.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textras)
                    .addComponent(texcvv)
                    .addComponent(codigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(64, 64, 64)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)))
                            .addComponent(jLabel4))
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addComponent(texdinero)
                    .addComponent(texcodigo))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texdinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texcvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int token = 0, dinero = 0, trans = 0, cvv = 0, resultadomas, resultadomenos;

        if (texcodigo.getText().equals("") || texdinero.getText().equals("") || textras.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "PORFAVOR INGRESE TODOS LOS DATOS");
        } else {
            if (texcodigo.getText().matches("[+-]?\\d*(\\.\\d+)?") && texdinero.getText().matches("[+-]?\\d*(\\.\\d+)?") && textras.getText().matches("[+-]?\\d*(\\.\\d+)?") && texcvv.getText().matches("[+-]?\\d*(\\.\\d+)?")) {
                token = Integer.parseInt(texcodigo.getText());
                dinero = Integer.parseInt(texdinero.getText());
                trans = Integer.parseInt(textras.getText());
                cvv = Integer.parseInt(texcvv.getText());
                if (variante == token) {
                    if (agregargente.getLista().get(intro.getNumero()).getPlata() >= dinero && buscarnumerodecuenta(trans) && agregargente.getLista().get(intro.getNumero()).getCvv() == cvv) {
                        resultadomenos = agregargente.getLista().get(intro.getNumero()).getPlata() - dinero;
                        resultadomas = agregargente.getLista().get(numero(trans)).getPlata() + dinero;
                        agregargente.getLista().get(intro.getNumero()).setPlata(resultadomenos);
                        agregargente.getLista().get(numero(trans)).setPlata(resultadomas);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "PORFAVOR INGRESE TODOS LOS DATOS CORRETAMENTE ");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "PORFAVOR INGRESE TODOS LOS DATOS CORRETAMENTE DEL CODIGO DE MOVIENTO BANCARIO");
                }
            } else {
                JOptionPane.showMessageDialog(null, "PORFAVOR INGRESE TODOS LOS DATOS CORRETAMENTE NUMERICOS");
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void texcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texcodigoActionPerformed

    private void textrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textrasActionPerformed

    private boolean buscarnumerodecuenta(int trans) {
        for (persona per : agregargente.getLista()) {
            if (per.getNumerodetrans() == trans) {
                return true;
            }
        }
        return false;
    }

    private int numero(int numero2) {
   
        numeroescogido = 0;
        for (persona per : agregargente.getLista()) {
            if (per.getNumerodetrans() == numero2 && agregargente.getLista().get(movientos.getNumero()).getNumerodetrans() !=numero2) {
                return numeroescogido;
            }
            numeroescogido++;
        }
        return numeroescogido;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                transferir dialog = new transferir(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public String getTexdinero() {
        return texdinero.getText();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField texcodigo;
    private javax.swing.JTextField texcvv;
    private javax.swing.JTextField texdinero;
    private javax.swing.JTextField textras;
    // End of variables declaration//GEN-END:variables
}
